CREATE TABLE IF NOT EXISTS product (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               name VARCHAR(255) NOT NULL,
                               description VARCHAR(1024),
                               category VARCHAR(100) NOT NULL,
                               price DECIMAL(12,2) NOT NULL,
                               stock INT NOT NULL,
                               sku VARCHAR(255),
                               active BOOLEAN NOT NULL,
                               created_at TIMESTAMP NOT NULL,
                               updated_at TIMESTAMP NOT NULL
                           );